seed: 6198
dry_run: false
no_pre_train_checkpoint: true

wandb:
  entity: xukai
  project: olmoe
  group: null

model:
  d_model: 1024 # 2048
  n_heads: 16 # 16
  n_layers: 16 # 16
  mlp_ratio: 1
  weight_tying: false
  alibi: false
  rope: true
  flash_attention: true
  attention_dropout: 0.0
  attention_layer_norm: true
  include_bias: false
  block_type: moe
  layer_norm_type: rms
  layer_norm_with_affine: true
  bias_for_layer_norm: false
  attention_layer_norm_with_affine: true
  activation_type: swiglu
  residual_dropout: 0.0
  embedding_dropout: 0.0
  max_sequence_length: 4096
  vocab_size: 50280
  embedding_size: 50304
  eos_token_id: 0
  pad_token_id: 1
  init_device: meta
  init_fn: normal
  init_std: 0.02
  init_cutoff_factor: 3
  moe_top_k: 4 # 8
  moe_num_experts: 32 # 64
  moe_dropless: true
  moe_mlp_impl: sparse
  moe_zloss_weight: 1e-9 # 0.001 # z-loss
  moe_loss_weight: 1e-9 # 0.01 # load balancing loss
  variational: true
  variational_approx: 1
  moe_kl_weight: 0.005 # kl loss

compile: null

optimizer:
  name: adamw
  learning_rate: 4.0e-4
  eps: 1.0e-8
  weight_decay: 0.1
  decay_norm_and_bias: true
  decay_embeddings: true
  betas:
  - 0.9
  - 0.95
  metrics_log_interval: 10

scheduler:
  name: cosine_with_warmup
  units: tokens
  t_warmup: 10485760000
  t_max: 5e12
  alpha_f: 0.1

tokenizer:
  identifier: tokenizers/allenai_gpt-neox-olmo-dolma-v1_5.json
  truncate_direction: right

save_folder: runs/${run_name}
save_overwrite: false

save_interval: 50
save_interval_ephemeral: null
save_num_checkpoints_to_keep: -1
sharded_checkpointer: olmo_core

save_interval_unsharded: null
save_num_unsharded_checkpoints_to_keep: -1

load_path: null

max_duration: 4ep
global_train_batch_size: 1024
device_train_microbatch_size: 128

precision: amp_bf16
distributed_strategy: fsdp

fsdp:
  wrapping_strategy: by_block
  precision: mixed
  sharding_strategy: FULL_SHARD

max_grad_norm: 1.0
max_grad_norm_ratio: null

speed_monitor:
  window_size: 1

eval_interval: 50
eval_subset_num_batches: -1
device_eval_batch_size: ${device_train_microbatch_size}
evaluators:
  - label: all-small-ppl-validation
    data:
      num_workers: 0
      drop_last: true
      datasets:
        minipile-validation:
          - /home/lab/moe/data/preprocessed/minipile/validation/part-0-00000.npy
  - label: all-small-ppl-test
    data:
      num_workers: 0
      drop_last: true
      datasets:
        minipile-test:
          - /home/lab/moe/data/preprocessed/minipile/test/part-0-00000.npy

data:
  pad_direction: right
  num_workers: 32
  drop_last: true
  pin_memory: true
  prefetch_factor: 8
  persistent_workers: true
  timeout: 0
  instance_filter:
      repetition_max_period: 13
      repetition_min_period: 1
      repetition_max_count: 32  
  paths:
    - /home/lab/moe/data/preprocessed/minipile/train/part-0-00000.npy
